package: quick_navigation
version: '3.5.5-dev'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/quick_navigation
perm: quick_navigation[]

page:
    title: translate:quicknavi_title
    icon: rex-icon fa-star
    perm: quick_navigation[settings]
    subpages:
        config: { title: 'translate:quicknavi_config' }
requires:
    packages:
        structure/content: '^2.1.0'
    redaxo: '^5.5.0'
conflicts:
    packages:
        yform: '<2.0.0'
        watson: '<2.1.0'
