package: quick_navigation
version: '1.3.1'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/quick_navigation

requires:
    packages:
        structure/content: '^2.1.0'
    redaxo: '^5.1.0'
