package: quick_navigation
version: '0.6.1'
author: 'Friends Of REDAXO'
supportpage: https://github.com/friendsofredaxo/

requires:
    packages:
        structure/content: '^2.1.0'
    redaxo: '^5.1.0'
