package: quick_navigation
version: '1.4dev'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/quick_navigation

page:
    title: 'Quick Navigation'
    perm: quick_navigation[]
    icon: rex-icon fa-star
    subpages:
        config: { title: 'translate:quicknavi_config' }


requires:
    packages:
        structure/content: '^2.1.0'
    redaxo: '^5.1.0'
